eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    preferIpAddress: true
  client:
    service-url:
      defaultZone:  http://discovery:8761/eureka

      
zuul:
  routes:
    employees: 
      path: /employees/**
      service-id: employee-service
